[server]
headless = true
runOnSave = false

[client]
toolbarMode = "viewer"
showErrorDetails = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0f766e"
backgroundColor = "#fbfbf8"
secondaryBackgroundColor = "#eef6f5"
textColor = "#111827"
